import "./globals.css";
import "primereact/resources/themes/viva-dark/theme.css";
import "primeicons/primeicons.css";
import type { Metadata } from "next";
import { PrimeReactProvider, APIOptions } from "primereact/api";
import AppSidebar from "./_layout/sidebar/sidebar";
import QueryProvider from '@/provider/queryProvider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const value: APIOptions = {
    appendTo: "self",
  };

  return (
    <html lang="en">
      <PrimeReactProvider value={value}>
        <body className="h-screen w-screen flex flex-col gap-2">
          <header>
            <AppSidebar />
          </header>
          <main className="flex-1">
            <QueryProvider>
              {children}
            </QueryProvider>
          </main>
        </body>
      </PrimeReactProvider>
    </html>
  );
}
